import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    padding: 10,
  },
  productInfo: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  img: {
    height: 150,
    width: 150,
    borderRadius: 75,
    marginTop: -50,
    marginLeft: 32,
  },
  starsContainer: {
    display: "flex",
    flexDirection: "row",
  },
  reviewCount: {
    fontSize: 17,
    fontWeight: "bold",
  },
  reviewContainer: {
    marginRight: 32,
    marginTop: 28,
  },
  btnUnit: {
    marginBottom: 40,
    borderRadius: 35,
    backgroundColor: "#e9f7e3",
    paddingVertical: 8,
    paddingHorizontal: 12,
    color: "#fff",
    width: "30%",
  },
  btnUnitText: {
    fontWeight: "900",
    fontSize: 16,
    textAlign: "center",
  },
  btnUnitActiveText: {
    color: "#fff",
    fontWeight: "900",
    fontSize: 16,
    textAlign: "center",
  },
  btnUnitActive: {
    marginBottom: 40,
    borderRadius: 35,
    backgroundColor: "#44994d",
    paddingVertical: 8,
    paddingHorizontal: 12,
    width: "30%",
  },
  unitContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  title: {
    fontSize: 20,
    fontWeight: "900",
    marginVertical: 12,
    marginTop: 20,
  },
  minus: {
    borderStyle: "solid",
    borderColor: "#999",
    borderWidth: 1,
    width: 32,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: 32,
    borderBottomLeftRadius: 8,
    borderTopLeftRadius: 8,
    paddingLeft: 1,
  },
  plus: {
    borderStyle: "solid",
    borderColor: "#999",
    borderWidth: 1,
    width: 32,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: 32,
    borderBottomRightRadius: 8,
    borderTopRightRadius: 8,
    paddingLeft: 1,
  },
  quantityWrapper: {
    marginTop: -30,
  },
  quantityControll: {
    display: "flex",
    flexDirection: "row",
  },
  quantity: {
    width: 40,
    textAlign: "center",
    borderBottomStyle: "solid",
    borderBottomColor: "#999",
    borderBottomWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "#999",
    borderTopWidth: 1,
    fontSize: 18,
    textAlignVertical: "center",
  },
  sliderContainer: {
    width: "50%",
    display: "flex",
    // flexDirection: "row",
  },
  strengthValue: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
  },
  currentStrengthValue: {
    fontWeight: "900",
    width: 32,
    fontSize: 24,
    marginLeft: 8,
    textAlign: "right",
  },
  currentStrengthMaxValue: {
    fontWeight: "900",
    width: 24,
  },
  wrapper: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  total: {
    fontWeight: "900",
    color: "#5fa762",
    fontSize: 21,
    // width: "20%",
  },
  reTotal: {
    fontWeight: "900",
    color: "#5fa762",
    fontSize: 21,
    textDecorationLine: "line-through",
    textDecorationStyle: "solid",
    // width: "20%",
  },
  totalText: {
    fontWeight: "900",
    fontSize: 21,
    // width: "40%",
  },
  totalContainer: {
    display: "flex",
    flexDirection: "row",
    backgroundColor: "#e9f7e3",
    padding: 8,
    borderRadius: 32,
    justifyContent: "center",
    marginTop: 12,
  },
  btnAddToCart: {
    width: "100%",
    marginBottom: 40,
    borderRadius: 35,
    backgroundColor: "#44994d",
    paddingVertical: 16,
    paddingHorizontal: 12,
    marginTop: 32,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  favoriteButton: {
    padding: 8,
  },
});
